# h2 database
# web console: http://192.168.99.100:81
# jdbc url: jdbc:h2:tcp://192.168.99.100:1521/dbname
h2:
  image: 'oscarfonts/h2'
  ports:
    - '1521:1521'
    - '81:81'
  volumes:
    - '/Users/kstefan/Dev/docker/data/h2:/opt/h2-data'

